// constants/images.js

export const muscleGroupImages = {
    "chest.png": require("../data/exercises/images/muscles/chest.png"),
    "back.png": require("../data/exercises/images/muscles/back.png"),
    "shoulders.png": require("../data/exercises/images/muscles/shoulders.png"),
    "biceps.png": require("../data/exercises/images/muscles/biceps.png"),
    "triceps.png": require("../data/exercises/images/muscles/triceps.png"),
    "legs.png": require("../data/exercises/images/muscles/legs.png"),
    "abs.png": require("../data/exercises/images/muscles/abs.png"),
    //"other.png": require("../data/exercises/images/muscles/other.png"),
};

export const exerciseImages = {
    "skull_crusher.gif": require("../data/exercises/images/exercises/triceps/skull_crusher.gif"),
    "pull_up.gif": require("../data/exercises/images/exercises/back/pull_up.gif"),
    "close_grip_pull_up.gif": require("../data/exercises/images/exercises/back/close_grip_pull_up.gif"),
    "wide_grip_seated_row.gif": require("../data/exercises/images/exercises/back/wide_grip_seated_row.gif"),
    "close_grip_seated_row.gif": require("../data/exercises/images/exercises/back/close_grip_seated_row.gif"),
    "wide_grip_lat_pulldown.gif": require("../data/exercises/images/exercises/back/wide_grip_lat_pulldown.gif"),
    "close_grip_lat_pulldown.gif": require("../data/exercises/images/exercises/back/close_grip_lat_pulldown.gif"),
    "barbell_row.gif": require("../data/exercises/images/exercises/back/barbell_row.gif"),
    "dumbbell_shrug.gif": require("../data/exercises/images/exercises/back/dumbbell_shrug.gif"),
    "deadlift.gif": require("../data/exercises/images/exercises/back/deadlift.gif"),
    "bench_press.gif": require("../data/exercises/images/exercises/chest/bench_press.gif"),
    "incline_bench_press.gif": require("../data/exercises/images/exercises/chest/incline_bench_press.gif"),
    "dumbbell_bench_press.gif": require("../data/exercises/images/exercises/chest/dumbbell_bench_press.gif"),
    "incline_dumbbell_press.gif": require("../data/exercises/images/exercises/chest/incline_dumbbell_press.gif"),
    "pec_fly.gif": require("../data/exercises/images/exercises/chest/pec_fly.gif"),
    "cable_crossover.gif": require("../data/exercises/images/exercises/chest/cable_crossover.gif"),
    "dips_chest.gif": require("../data/exercises/images/exercises/chest/dips_chest.gif"),
    "push_up.gif": require("../data/exercises/images/exercises/chest/push_up.gif"),
    "machine_chest_press.gif": require("../data/exercises/images/exercises/chest/machine_chest_press.gif"),
    "arnold_press.gif": require("../data/exercises/images/exercises/shoulder/arnold_press.gif"),
    "military_press.gif": require("../data/exercises/images/exercises/shoulder/military_press.gif"),
    "barbell_shoulder_press.gif": require("../data/exercises/images/exercises/shoulder/barbell_shoulder_press.gif"),
    "machine_shoulder_press.gif": require("../data/exercises/images/exercises/shoulder/machine_shoulder_press.gif"),
    "rear_delt_fly.gif": require("../data/exercises/images/exercises/shoulder/rear_delt_fly.gif"),
    "rear_delt_raise.gif": require("../data/exercises/images/exercises/shoulder/rear_delt_raise.gif"),
    "dumbbell_front_raise.gif": require("../data/exercises/images/exercises/shoulder/dumbbell_front_raise.gif"),
    "cable_front_raise.gif": require("../data/exercises/images/exercises/shoulder/cable_front_raise.gif"),
    "dumbbell_lateral_raise.gif": require("../data/exercises/images/exercises/shoulder/dumbbell_lateral_raise.gif"),
    "cable_lateral_raise.gif": require("../data/exercises/images/exercises/shoulder/cable_lateral_raise.gif"),
    "barbell_curl.gif": require("../data/exercises/images/exercises/biceps/barbell_curl.gif"),
    "preacher_curl.gif": require("../data/exercises/images/exercises/biceps/preacher_curl.gif"),
    "cable_biceps_hammer.gif": require("../data/exercises/images/exercises/biceps/cable_biceps_hammer.gif"),
    "cable_biceps_neutral.gif": require("../data/exercises/images/exercises/biceps/cable_biceps_neutral.gif"),
    "concentration_curl_hammer.gif": require("../data/exercises/images/exercises/biceps/concentration_curl_hammer.gif"),
    "concentration_curl_neutral.gif": require("../data/exercises/images/exercises/biceps/concentration_curl_neutral.gif"),
    "hammer_curl.gif": require("../data/exercises/images/exercises/biceps/hammer_curl.gif"),
    "dumbbell_curl.gif": require("../data/exercises/images/exercises/biceps/dumbbell_curl.gif"),
    "incline_dumbbell_curl.gif": require("../data/exercises/images/exercises/biceps/incline_dumbbell_curl.gif"),
    "incline_hammer_curl.gif": require("../data/exercises/images/exercises/biceps/incline_hammer_curl.gif"),
    "dips_triceps.gif": require("../data/exercises/images/exercises/triceps/dips_triceps.gif"),
    "machine_dips.gif": require("../data/exercises/images/exercises/triceps/machine_dips.gif"),
    "dumbbell_triceps_extension.gif": require("../data/exercises/images/exercises/triceps/dumbbell_triceps_extension.gif"),
    "cable_triceps_extension.gif": require("../data/exercises/images/exercises/triceps/cable_triceps_extension.gif"),
    "triceps_kickback.gif": require("../data/exercises/images/exercises/triceps/triceps_kickback.gif"),
    "overhead_triceps_extension.gif": require("../data/exercises/images/exercises/triceps/overhead_triceps_extension.gif"),
    "lying_triceps_extension.gif": require("../data/exercises/images/exercises/triceps/lying_triceps_extension.gif"),
    "hip_abduction.gif": require("../data/exercises/images/exercises/legs/hip_abduction.gif"),
    "hip_adduction.gif": require("../data/exercises/images/exercises/legs/hip_adduction.gif"),
    "dumbbell_calf_raise.gif": require("../data/exercises/images/exercises/legs/dumbbell_calf_raise.gif"),
    "dumbbell_lunge.gif": require("../data/exercises/images/exercises/legs/dumbbell_lunge.gif"),
    "hack_squat.gif": require("../data/exercises/images/exercises/legs/hack_squat.gif"),
    "seated_leg_curl.gif": require("../data/exercises/images/exercises/legs/seated_leg_curl.gif"),
    "lying_leg_curl.gif": require("../data/exercises/images/exercises/legs/lying_leg_curl.gif"),
    "leg_extension.gif": require("../data/exercises/images/exercises/legs/leg_extension.gif"),
    "leg_press.gif": require("../data/exercises/images/exercises/legs/leg_press.gif"),
    "barbell_squat.gif": require("../data/exercises/images/exercises/legs/barbell_squat.gif"),
    "dumbbell_squat.gif": require("../data/exercises/images/exercises/legs/dumbbell_squat.gif"),
    "floor_crunch.gif": require("../data/exercises/images/exercises/abs/floor_crunch.gif"),
    "incline_bench_crunch.gif": require("../data/exercises/images/exercises/abs/incline_bench_crunch.gif"),
    "cable_crunch.gif": require("../data/exercises/images/exercises/abs/cable_crunch.gif"),
    "oblique_crunch.gif": require("../data/exercises/images/exercises/abs/oblique_crunch.gif"),


};
