// constants/images.js

export const muscleGroupImages = {
    "chest.png": require("../data/exercises/images/muscles/chest.png"),
    "back.png": require("../data/exercises/images/muscles/back.png"),
    "shoulders.png": require("../data/exercises/images/muscles/shoulders.png"),
    "biceps.png": require("../data/exercises/images/muscles/biceps.png"),
    "triceps.png": require("../data/exercises/images/muscles/triceps.png"),
    "legs.png": require("../data/exercises/images/muscles/legs.png"),
    "abs.png": require("../data/exercises/images/muscles/abs.png"),
    //"other.png": require("../data/exercises/images/muscles/other.png"),
};

export const exerciseImages = {
    "skull_crusher.webp": require("../data/exercises/images/exercises/triceps/skull_crusher.webp"),
    "pull_up.webp": require("../data/exercises/images/exercises/back/pull_up.webp"),
    "close_grip_pull_up.webp": require("../data/exercises/images/exercises/back/close_grip_pull_up.webp"),
    "wide_grip_seated_row.webp": require("../data/exercises/images/exercises/back/wide_grip_seated_row.webp"),
    "close_grip_seated_row.webp": require("../data/exercises/images/exercises/back/close_grip_seated_row.webp"),
    "wide_grip_lat_pulldown.webp": require("../data/exercises/images/exercises/back/wide_grip_lat_pulldown.webp"),
    "close_grip_lat_pulldown.webp": require("../data/exercises/images/exercises/back/close_grip_lat_pulldown.webp"),
    "barbell_row.webp": require("../data/exercises/images/exercises/back/barbell_row.webp"),
    "dumbbell_shrug.webp": require("../data/exercises/images/exercises/back/dumbbell_shrug.webp"),
    "deadlift.webp": require("../data/exercises/images/exercises/back/deadlift.webp"),
    "bench_press.webp": require("../data/exercises/images/exercises/chest/bench_press.webp"),
    "incline_bench_press.webp": require("../data/exercises/images/exercises/chest/incline_bench_press.webp"),
    "dumbbell_bench_press.webp": require("../data/exercises/images/exercises/chest/dumbbell_bench_press.webp"),
    "incline_dumbbell_press.webp": require("../data/exercises/images/exercises/chest/incline_dumbbell_press.webp"),
    "pec_fly.webp": require("../data/exercises/images/exercises/chest/pec_fly.webp"),
    "cable_crossover.webp": require("../data/exercises/images/exercises/chest/cable_crossover.webp"),
    "dips_chest.webp": require("../data/exercises/images/exercises/chest/dips_chest.webp"),
    "push_up.webp": require("../data/exercises/images/exercises/chest/push_up.webp"),
    "machine_chest_press.webp": require("../data/exercises/images/exercises/chest/machine_chest_press.webp"),
    "arnold_press.webp": require("../data/exercises/images/exercises/shoulder/arnold_press.webp"),
    "military_press.webp": require("../data/exercises/images/exercises/shoulder/military_press.webp"),
    "barbell_shoulder_press.webp": require("../data/exercises/images/exercises/shoulder/barbell_shoulder_press.webp"),
    "machine_shoulder_press.webp": require("../data/exercises/images/exercises/shoulder/machine_shoulder_press.webp"),
    "rear_delt_fly.webp": require("../data/exercises/images/exercises/shoulder/rear_delt_fly.webp"),
    "rear_delt_raise.webp": require("../data/exercises/images/exercises/shoulder/rear_delt_raise.webp"),
    "dumbbell_front_raise.webp": require("../data/exercises/images/exercises/shoulder/dumbbell_front_raise.webp"),
    "cable_front_raise.webp": require("../data/exercises/images/exercises/shoulder/cable_front_raise.webp"),
    "dumbbell_lateral_raise.webp": require("../data/exercises/images/exercises/shoulder/dumbbell_lateral_raise.webp"),
    "cable_lateral_raise.webp": require("../data/exercises/images/exercises/shoulder/cable_lateral_raise.webp"),
    "barbell_curl.webp": require("../data/exercises/images/exercises/biceps/barbell_curl.webp"),
    "preacher_curl.webp": require("../data/exercises/images/exercises/biceps/preacher_curl.webp"),
    "cable_biceps_hammer.webp": require("../data/exercises/images/exercises/biceps/cable_biceps_hammer.webp"),
    "cable_biceps_neutral.webp": require("../data/exercises/images/exercises/biceps/cable_biceps_neutral.webp"),
    "concentration_curl_hammer.webp": require("../data/exercises/images/exercises/biceps/concentration_curl_hammer.webp"),
    "concentration_curl_neutral.webp": require("../data/exercises/images/exercises/biceps/concentration_curl_neutral.webp"),
    "hammer_curl.webp": require("../data/exercises/images/exercises/biceps/hammer_curl.webp"),
    "dumbbell_curl.webp": require("../data/exercises/images/exercises/biceps/dumbbell_curl.webp"),
    "incline_dumbbell_curl.webp": require("../data/exercises/images/exercises/biceps/incline_dumbbell_curl.webp"),
    "incline_hammer_curl.webp": require("../data/exercises/images/exercises/biceps/incline_hammer_curl.webp"),
    "dips_triceps.webp": require("../data/exercises/images/exercises/triceps/dips_triceps.webp"),
    "machine_dips.webp": require("../data/exercises/images/exercises/triceps/machine_dips.webp"),
    "dumbbell_triceps_extension.webp": require("../data/exercises/images/exercises/triceps/dumbbell_triceps_extension.webp"),
    "cable_triceps_extension.webp": require("../data/exercises/images/exercises/triceps/cable_triceps_extension.webp"),
    "triceps_kickback.webp": require("../data/exercises/images/exercises/triceps/triceps_kickback.webp"),
    "overhead_triceps_extension.webp": require("../data/exercises/images/exercises/triceps/overhead_triceps_extension.webp"),
    "lying_triceps_extension.webp": require("../data/exercises/images/exercises/triceps/lying_triceps_extension.webp"),
    "hip_abduction.webp": require("../data/exercises/images/exercises/legs/hip_abduction.webp"),
    "hip_adduction.webp": require("../data/exercises/images/exercises/legs/hip_adduction.webp"),
    "dumbbell_calf_raise.webp": require("../data/exercises/images/exercises/legs/dumbbell_calf_raise.webp"),
    "dumbbell_lunge.webp": require("../data/exercises/images/exercises/legs/dumbbell_lunge.webp"),
    "hack_squat.webp": require("../data/exercises/images/exercises/legs/hack_squat.webp"),
    "seated_leg_curl.webp": require("../data/exercises/images/exercises/legs/seated_leg_curl.webp"),
    "lying_leg_curl.webp": require("../data/exercises/images/exercises/legs/lying_leg_curl.webp"),
    "leg_extension.webp": require("../data/exercises/images/exercises/legs/leg_extension.webp"),
    "leg_press.webp": require("../data/exercises/images/exercises/legs/leg_press.webp"),
    "barbell_squat.webp": require("../data/exercises/images/exercises/legs/barbell_squat.webp"),
    "dumbbell_squat.webp": require("../data/exercises/images/exercises/legs/dumbbell_squat.webp"),
    "floor_crunch.webp": require("../data/exercises/images/exercises/abs/floor_crunch.webp"),
    "incline_bench_crunch.webp": require("../data/exercises/images/exercises/abs/incline_bench_crunch.webp"),
    "cable_crunch.webp": require("../data/exercises/images/exercises/abs/cable_crunch.webp"),
    "oblique_crunch.webp": require("../data/exercises/images/exercises/abs/oblique_crunch.webp"),


};
